sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bovito/dc-rc -f Dockerfile.dev .

script:
  - docker run -e CI=true bovito/dc-rc npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: dc_rc
  env: DcRc-env
  bucket_name: elasticbeanstalk-eu-north-1-109106504215
  bucket_path: dc_rc
  on:
    branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key:
    secure: "$SECRET_KEY"